### ISSUE TITLE
API Mappings

### ISSUE THREAD

**Issue by mopsalarm** [Graphicscore/Pr0#1]
Klassenhierarchie für API Entpoints bauen, so dass JSON auf GSON gemappt werden kann.
* http://pr0gramm.com/api/items/get?promoted=1
* http://pr0gramm.com/api/items/info?itemId=629582

**Comment by Graphicscore** [comment]
Wir müssen uns im IRC nochmal genau über die Klassenstruktur unterhalten, wie was genau etc.

**Comment by kratostav** [comment]
Hab da schon ei paar ideen

----- Ursprüngliche Nachricht -----
Von: "Dominik Louven" <notifications@github.com>
Gesendet: ‎14.‎02.‎2015 23:56
An: "Graphicscore/Pr0" <Pr0@noreply.github.com>
Betreff: Re: [Pr0] API Mappings (#1)

Wir müssen uns im IRC nochmal genau über die Klassenstruktur unterhalten, wie was genau etc.

**Comment by mopsalarm** [comment]
Hierbei bezieht sich das nur auf das Format der Antwort, die die pr0gramm api liefert. Damit gson aus der empfangenen json Datei automatisch Java Klassen machen kann.

**Comment by kratostav** [comment]
lasse meine windowsphoneapp in nexter zeit durch nen proxy laufen und werde euch die api calls mitteilen

**Comment by mopsalarm** [comment]
Im chrome oder Firefox einfach f12 drücken und den Netzwerk Tab aufrufen. Keine Notwendigkeit für Proxis. Api ist recht easy, habe ich schon für rep0st angeschaut.

**Comment by kratostav** [comment]
will aber die json api haben nicht den web teil.
wie läuft der login?

**Comment by mopsalarm** [comment]
Der Netzwerk Tab listet alle Netzwerk anfragen. Und die komplette website geht über die json api. Einfach mal öffnen und einloggen :)
