### ISSUE TITLE
Webm player restart

### ISSUE THREAD

**Issue by kratostav** [Graphicscore/Pr0#7]
Meine idee ist es das webm zuerst herunterzuladen und dann in den cache zu schreiben.
Dann erst in den Player laden.
wenn das Handy gedreht wird in der onPause die Zeit gemerkt.
in der onResume wieder zurückgeschrieben und das file aus dem storage geladen und die zeit gesetzt.
Player ist trotzdem kurz weck aber:
+File muss nicht neu geladen werden (daten+zeit ersparnis)
+player springt zurück zum vorherigen Zeitpunkt (vorallem für längere WebMs sinnvoll)

dass der Player immer da bleibt müsste ein service geschrieben werden und dann könnte der player sogar im hintergrund laufen sie wie bei youtube oder Deezer/Spotify.
aber das ist für unsere zwecke nicht zweckmäßig.

Ich bin sowieso dafür dass alles gecacht wird.

Was sagt ihr dazu?

**Comment by mopsalarm** [comment]
Ich bin nicht ganz begeistert. Komplett herunterladen des webm kommt nicht in Frage. Das würde zu mehreren Sekunden Wartezeit führen, bevor es anhängt zu spielen. Abgesehen von webm wird bereits alles gecached. 
Das Starten eines lokalen Service pro Video könnte jedoch tatsächlich helfen. Dieser kann den MediaPlayer halten.

**Comment by mopsalarm** [comment]
Wir sind allerdings innerhalb einer View an der Stelle. Vllt sollte der Player lieber in ein Fragment raus gezogen werden

**Comment by kratostav** [comment]
ja das ist keine schlechte idee kannst du das machen?

**Comment by mopsalarm** [comment]
Bestimmt, ja. Aber nicht mehr heute. Werde gleich noch aus meinem Keller raus und unter Leute.
Du kannst das auch gerne ausprobieren. Wenn du dir das nciht zutraust, gäbe es sonst noch genug andere und einfacherere Baustellen

**Comment by kratostav** [comment]
naja fragments ist nicht so mein ding...
was wäre sonst noch zu machen?

**Comment by mopsalarm** [comment]
Ich lege mal ein paar Issues an mit Dingen, die mir gerade einfallen.
